### ISSUE TITLE
Tareas para usuario autenticado (C)

### ISSUE THREAD

**Issue by Francisco-Borrego** [Francisco-Borrego/Acme-Planner#3]
Implementar la funcionalidad necesaria para que un usuario autenticado pueda listar tareas (finalizadas y poder ordenar por periodo de ejecución o carga de trabajo), además de poder ver los detalles de estas.

**Comment by serarirud** [comment]
Las tareas tienen que mostrar únicamente el título, la carga de trabajo, la fecha de inicio y la fecha de fin, además de esto se añadirá un botón para ver más detalles el cual redirigirá al usuario a otra vista con el resto de atributos.
